### ISSUE TITLE
Adaptive timestepping for partitioned symplectic methods

### ISSUE THREAD

**Issue by gabrielfougeron** [JuliaGNI/GeometricIntegrators.jl#174]
Hi,

I see in the docs that this repository implements explicit and implicit partitionned symplectic RK methods: 
 https://docs.juliahub.com/GeometricIntegrators/fhpp1/0.11.4/integrators/rk/

I am too creating a (much smaller) python code aiming at doing this, and I'm looking for some advice concerning adaptive timestepping.
Hence the questions: do you have adaptive timestepping capabilities that preserve symplecticity? If yes, could you please explain the concept or point me to a reference?

Thank you

**Comment by michakraus** [comment]
Hi Gabriel,

Please apologise the late reply. This is a very interesting question and not easy to answer. In GeometricIntegrators, we can in principle support time-adaptive methods, but we haven't implemented any, yet.

The canonical reference (Hairer, Lubich, Wanner: Geometric Numerical Integration) touches upon this in Section VIII.2.1. But there are not many details.

On the front of variational integrators, there is some discussion in Marsden, West (2001): Discrete mechanics and variational integrators, Section 4.9.

Other than that, a quick google search leads you to recent work in this area. Some references I am familiar with are

https://doi.org/10.1088/0741-3335/54/1/014004
https://doi.org/10.1007/s10569-012-9441-z
https://doi.org/10.1007/s11075-018-0636-6
https://doi.org/10.3934/jgm.2023010

**Comment by gabrielfougeron** [comment]
Thanks Michael for your answer.

Indeed, I'm familiar with the Hairer Lublich Wanner, but (unless I misunderstood) they do not present an adaptive timestepping method that conserves both sympecticity and the partitioned structure. I'll definitely have a look at the references you provided.

Cheers
